package com.captain.mapper.special;

import com.captain.entity.gen.UnionMember;
import com.captain.entity.gen.UnionMemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UnionMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_union_member
     *
     * @mbg.generated Thu Mar 22 10:49:59 CST 2018
     */
    long countByExample(UnionMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_union_member
     *
     * @mbg.generated Thu Mar 22 10:49:59 CST 2018
     */
    int deleteByExample(UnionMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_union_member
     *
     * @mbg.generated Thu Mar 22 10:49:59 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_union_member
     *
     * @mbg.generated Thu Mar 22 10:49:59 CST 2018
     */
    int insert(UnionMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_union_member
     *
     * @mbg.generated Thu Mar 22 10:49:59 CST 2018
     */
    int insertSelective(UnionMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_union_member
     *
     * @mbg.generated Thu Mar 22 10:49:59 CST 2018
     */
    List<UnionMember> selectByExample(UnionMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_union_member
     *
     * @mbg.generated Thu Mar 22 10:49:59 CST 2018
     */
    UnionMember selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_union_member
     *
     * @mbg.generated Thu Mar 22 10:49:59 CST 2018
     */
    int updateByExampleSelective(@Param("record") UnionMember record, @Param("example") UnionMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_union_member
     *
     * @mbg.generated Thu Mar 22 10:49:59 CST 2018
     */
    int updateByExample(@Param("record") UnionMember record, @Param("example") UnionMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_union_member
     *
     * @mbg.generated Thu Mar 22 10:49:59 CST 2018
     */
    int updateByPrimaryKeySelective(UnionMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_union_member
     *
     * @mbg.generated Thu Mar 22 10:49:59 CST 2018
     */
    int updateByPrimaryKey(UnionMember record);


}