package com.captain.mapper;

import com.captain.entity.gen.Union;
import com.captain.entity.gen.UnionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UnionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_special
     *
     * @mbg.generated Thu Mar 22 10:48:38 CST 2018
     */
    long countByExample(UnionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_special
     *
     * @mbg.generated Thu Mar 22 10:48:38 CST 2018
     */
    int deleteByExample(UnionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_special
     *
     * @mbg.generated Thu Mar 22 10:48:38 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_special
     *
     * @mbg.generated Thu Mar 22 10:48:38 CST 2018
     */
    int insert(Union record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_special
     *
     * @mbg.generated Thu Mar 22 10:48:38 CST 2018
     */
    int insertSelective(Union record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_special
     *
     * @mbg.generated Thu Mar 22 10:48:38 CST 2018
     */
    List<Union> selectByExampleWithBLOBs(UnionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_special
     *
     * @mbg.generated Thu Mar 22 10:48:38 CST 2018
     */
    List<Union> selectByExample(UnionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_special
     *
     * @mbg.generated Thu Mar 22 10:48:38 CST 2018
     */
    Union selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_special
     *
     * @mbg.generated Thu Mar 22 10:48:38 CST 2018
     */
    int updateByExampleSelective(@Param("record") Union record, @Param("example") UnionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_special
     *
     * @mbg.generated Thu Mar 22 10:48:38 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Union record, @Param("example") UnionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_special
     *
     * @mbg.generated Thu Mar 22 10:48:38 CST 2018
     */
    int updateByExample(@Param("record") Union record, @Param("example") UnionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_special
     *
     * @mbg.generated Thu Mar 22 10:48:38 CST 2018
     */
    int updateByPrimaryKeySelective(Union record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_special
     *
     * @mbg.generated Thu Mar 22 10:48:38 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Union record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_special
     *
     * @mbg.generated Thu Mar 22 10:48:38 CST 2018
     */
    int updateByPrimaryKey(Union record);

    List<Union> getAllUnion();
}